<?php
// module/Album/view/album/album/add.phtml:

$title = 'Add new produto';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
$form->setAttribute('action', $this->url('loja', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id_produto'));
echo $this->formRow($form->get('nome'));

echo $this->formRow($form->get('imagem'));
echo $this->formRow($form->get('validade'));

echo $this->formRow($form->get('qtd_estoque'));
echo $this->formRow($form->get('custo'));

echo $this->formRow($form->get('preco'));
echo $this->formRow($form->get('categoria'));

echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();