<?php
// module/Album/view/album/album/index.phtml:

$title = 'My albums';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('loja', ['action' => 'add']) ?>">Add new album</a>
</p>

<table class="table">
<tr>
    <th>nome</th>
    <th>telefone</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($pessoas as $pessoa) : ?>
    <tr>
        <td><?= $this->escapeHtml($pessoa->getNome()) ?></td>
        <td><?= $this->escapeHtml($pessoa->getTelefone()) ?></td>
        <td>
            <a href="<?= $this->url('loja', ['action' => 'edit', 'id' => $pessoa->getId_pessoa()]) ?>">Edit</a>
            <a href="<?= $this->url('loja', ['action' => 'delete', 'id' => $pessoa->getId_pessoa()]) ?>">Delete</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>